# Generated by Django 4.2.20 on 2025-06-03 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='total_assessment_time',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QuestionTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.BigIntegerField()),
                ('end_time', models.BigIntegerField()),
                ('response_time', models.FloatField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_generator.assessmentquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_timings', to='quiz_generator.assessmentsession')),
            ],
            options={
                'unique_together': {('session', 'question')},
            },
        ),
    ]
