# Generated by Django 4.2.20 on 2025-06-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_generator', '0003_alter_assessmentquestion_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresponse',
            name='condition_type',
            field=models.CharField(choices=[('dyslexia', 'Dyslexia'), ('autism', 'Autism')], default='dyslexia', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='questiontiming',
            name='condition_type',
            field=models.CharField(choices=[('dyslexia', 'Dyslexia'), ('autism', 'Autism')], default='dyslexia', max_length=20),
        ),
        migrations.AddField(
            model_name='questiontiming',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], default='moderate', max_length=20),
        ),
    ]
