# Generated by Django 4.2.20 on 2025-06-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_generator', '0004_assessmentresponse_condition_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='assessment_type',
            field=models.CharField(choices=[('dyslexia', 'Dyslexia Only'), ('autism', 'Autism Only'), ('both', 'Both Assessments')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='autism_score',
            field=models.FloatField(blank=True, help_text='Score for autism questions only', null=True),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='dyslexia_score',
            field=models.FloatField(blank=True, help_text='Score for dyslexia questions only', null=True),
        ),
    ]
