# Generated by Django 4.2.20 on 2025-06-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_generator', '0005_assessmentsession_assessment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='customization_reason',
            field=models.TextField(blank=True, help_text='Reason for difficulty customization', null=True),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='difficulty_customized',
            field=models.BooleanField(default=False, help_text='Whether difficulty distribution was customized'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='has_reading_difficulty',
            field=models.BooleanField(default=False, help_text='Whether student has known reading difficulties'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='needs_assistance',
            field=models.BooleanField(default=False, help_text='Whether student needs assistance during assessment'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='previous_assessment',
            field=models.BooleanField(default=False, help_text='Whether student has taken similar assessments before'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='primary_language',
            field=models.CharField(blank=True, default='English', help_text="Student's primary language", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='reading_level',
            field=models.CharField(blank=True, help_text="Student's reading proficiency level", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='student_age',
            field=models.IntegerField(blank=True, help_text="Student's age at time of assessment", null=True),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='student_grade',
            field=models.CharField(blank=True, help_text="Student's current grade level", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='visual_assessment_recommended',
            field=models.BooleanField(default=False, help_text='Whether visual assessment was recommended'),
        ),
    ]
