# Generated by Django 4.2.20 on 2025-06-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='assessment_score',
            field=models.FloatField(blank=True, help_text='Assessment accuracy percentage (0-100)', null=True),
        ),
    ]
