# Generated by Django 4.2.20 on 2025-06-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_studentprofile_assessment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='assessment_type',
            field=models.CharField(blank=True, choices=[('dyslexia', 'Dyslexia Only'), ('autism', 'Autism Only'), ('both', 'Both Assessments')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='autism_score',
            field=models.FloatField(blank=True, help_text='Autism assessment score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='dyslexia_score',
            field=models.FloatField(blank=True, help_text='Dyslexia assessment score (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='assessment_score',
            field=models.FloatField(blank=True, help_text='Overall assessment accuracy percentage (0-100)', null=True),
        ),
    ]
