# Generated by Django 5.2.2 on 2025-06-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_studentprofile_autism_prediction_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text="Student's age", null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='grade_level_detailed',
            field=models.CharField(blank=True, help_text="Student's grade level (Elementary, Middle School, etc.)", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='has_reading_difficulty',
            field=models.BooleanField(default=False, help_text='Does the student have reading difficulties?'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='needs_assistance',
            field=models.BooleanField(default=False, help_text='Does the student need special assistance?'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pre_assessment_completed',
            field=models.BooleanField(default=False, help_text='Has the student completed the pre-assessment form?'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pre_assessment_date',
            field=models.DateTimeField(blank=True, help_text='When the pre-assessment was completed', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='previous_assessment',
            field=models.BooleanField(default=False, help_text='Has the student taken assessments before?'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='primary_language',
            field=models.CharField(default='English', help_text="Student's primary language", max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='reading_level',
            field=models.CharField(blank=True, help_text="Student's reading level", max_length=50, null=True),
        ),
    ]
