# Generated by Django 4.2.20 on 2025-05-31 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('accessibility', 'Accessibility'), ('dyslexia_support', 'Dyslexia Support'), ('technical', 'Technical'), ('feature_request', 'Feature Request'), ('other', 'Other')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DyslexiaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonological_awareness_score', models.PositiveIntegerField(blank=True, null=True)),
                ('visual_processing_score', models.PositiveIntegerField(blank=True, null=True)),
                ('working_memory_score', models.PositiveIntegerField(blank=True, null=True)),
                ('processing_speed_score', models.PositiveIntegerField(blank=True, null=True)),
                ('reading_difficulty_level', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10, null=True)),
                ('spelling_difficulty', models.BooleanField(default=False)),
                ('writing_difficulty', models.BooleanField(default=False)),
                ('math_difficulty', models.BooleanField(default=False)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('recommended_accommodations', models.TextField(blank=True, null=True)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dyslexia_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessibilitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dyslexia_mode', models.CharField(choices=[('none', 'None'), ('phonological', 'Phonological'), ('surface', 'Surface'), ('visual', 'Visual')], default='none', max_length=20)),
                ('syllable_highlighting', models.BooleanField(default=False)),
                ('word_emphasis', models.BooleanField(default=False)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('font_family', models.CharField(choices=[('default', 'Default'), ('opendyslexic', 'OpenDyslexic'), ('lexend', 'Lexend')], default='default', max_length=20)),
                ('line_spacing', models.CharField(choices=[('normal', 'Normal'), ('wide', 'Wide'), ('wider', 'Wider')], default='normal', max_length=10)),
                ('letter_spacing', models.CharField(choices=[('normal', 'Normal'), ('wide', 'Wide'), ('wider', 'Wider')], default='normal', max_length=10)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('high_contrast', 'High Contrast'), ('dyslexia_friendly', 'Dyslexia Friendly')], default='light', max_length=20)),
                ('custom_background_color', models.CharField(blank=True, max_length=7, null=True)),
                ('custom_text_color', models.CharField(blank=True, max_length=7, null=True)),
                ('text_to_speech_enabled', models.BooleanField(default=False)),
                ('speech_rate', models.FloatField(default=1.0, help_text='Speech rate multiplier')),
                ('speech_volume', models.FloatField(default=1.0, help_text='Speech volume (0.0 to 1.0)')),
                ('keyboard_navigation', models.BooleanField(default=False)),
                ('reduced_motion', models.BooleanField(default=False)),
                ('focus_indicators', models.BooleanField(default=True)),
                ('reading_guide', models.BooleanField(default=False)),
                ('text_highlighting', models.BooleanField(default=False)),
                ('auto_scroll', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessibilityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('setting_changed', 'Setting Changed'), ('feature_used', 'Feature Used'), ('assistance_requested', 'Assistance Requested'), ('error_encountered', 'Error Encountered')], max_length=30)),
                ('feature_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
