# Generated by Django 5.2.2 on 2025-07-21 12:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('min_age', models.PositiveIntegerField()),
                ('max_age', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['min_age'],
            },
        ),
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('clinical_significance', models.TextField(blank=True, help_text='What this category measures clinically')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight of this category in overall scoring (0.1-5.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Task Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('max_possible_score', models.PositiveIntegerField(default=0)),
                ('accuracy_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('risk_indicators', models.JSONField(blank=True, default=dict, help_text='Risk indicators by category')),
                ('pre_assessment_data', models.JSONField(blank=True, default=dict, help_text='Age, grade, reading level, etc.')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dyslexia_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title for admin reference', max_length=200)),
                ('question_text', models.TextField(help_text='The main question text')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('text_response', 'Open Text Response'), ('sequencing', 'Sequencing/Ordering'), ('matching', 'Matching'), ('audio_response', 'Audio Response')], max_length=20)),
                ('grade_levels', models.CharField(blank=True, help_text="e.g., 'K-2', '3-5', '6-8'", max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assessment_images/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='assessment_audio/')),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for this question')),
                ('audio_instructions', models.FileField(blank=True, help_text='Audio version of instructions', null=True, upload_to='instruction_audio/')),
                ('points', models.PositiveIntegerField(default=1, help_text='Points awarded for correct answer')),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Time limit in seconds (optional)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Extra data for sequencing, matching, etc.')),
                ('age_ranges', models.ManyToManyField(blank=True, to='dyslexia_assessment.agerange')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('difficulty_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyslexia_assessment.difficultylevel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dyslexia_assessment.taskcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('option_image', models.ImageField(blank=True, null=True, upload_to='option_images/')),
                ('option_audio', models.FileField(blank=True, null=True, upload_to='option_audio/')),
                ('order', models.PositiveIntegerField(default=1)),
                ('explanation', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='dyslexia_assessment.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True, help_text='For open-ended questions')),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='For complex responses (sequencing, matching, etc.)')),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('score_earned', models.PositiveIntegerField(default=0)),
                ('auto_scored', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyslexia_assessment.question')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_responses', to=settings.AUTH_USER_MODEL)),
                ('selected_option', models.ForeignKey(blank=True, help_text='For multiple choice questions', null=True, on_delete=django.db.models.deletion.CASCADE, to='dyslexia_assessment.questionoption')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='dyslexia_assessment.assessmentsession')),
            ],
            options={
                'ordering': ['answered_at'],
                'unique_together': {('session', 'question')},
            },
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='questions',
            field=models.ManyToManyField(through='dyslexia_assessment.StudentResponse', to='dyslexia_assessment.question'),
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('randomize_questions', models.BooleanField(default=True)),
                ('max_questions', models.PositiveIntegerField(blank=True, help_text='Maximum number of questions to include (leave blank for all)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(blank=True, to='dyslexia_assessment.question')),
                ('target_age_ranges', models.ManyToManyField(blank=True, to='dyslexia_assessment.agerange')),
                ('target_categories', models.ManyToManyField(blank=True, to='dyslexia_assessment.taskcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
